# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [5]:
import torch


# Create random tensor
tensor1 =torch.rand(7,7)
tensor1

tensor([[0.4315, 0.1352, 0.8207, 0.8651, 0.2280, 0.7298, 0.4784],
        [0.5738, 0.5735, 0.2691, 0.2423, 0.2559, 0.8435, 0.7739],
        [0.0066, 0.7460, 0.9296, 0.9987, 0.0715, 0.5274, 0.0604],
        [0.5181, 0.4614, 0.2805, 0.4406, 0.9780, 0.4296, 0.1217],
        [0.1381, 0.4758, 0.2558, 0.5627, 0.6410, 0.0757, 0.0486],
        [0.3785, 0.4425, 0.3578, 0.6442, 0.5038, 0.8534, 0.6840],
        [0.4347, 0.1191, 0.2972, 0.6818, 0.6805, 0.4433, 0.3898]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [14]:
# Create another random tensor
tensor2 = torch.rand(1,7)
# Perform matrix multiplication 
x=torch.matmul(tensor1,tensor2.T)
x

tensor([[2.0304],
        [1.6544],
        [2.0378],
        [1.3014],
        [1.0736],
        [1.8938],
        [1.4427]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [19]:
# Set manual seed
Random_seed = 0

# Create two random tensors
torch.manual_seed(Random_seed)
tensorA =torch.rand( 7,7)
torch.manual_seed(Random_seed)
tensorb = torch.rand(1,7)


# Matrix multiply tensors
x= torch.matmul(tensorA,tensorb.T)

x,x.shape


(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]), torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [20]:
# Set random seed on the GPU
randomseed = 1234
torch.cuda.manual_seed(randomseed)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [27]:
# Set random seed
randomseed = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
# Create two random tensors on GPU
torch.cuda.manual_seed(randomseed)
tensorx = torch.rand(2,3).to(device)
torch.cuda.manual_seed(randomseed)
tensory = torch.rand(2,3).to(device)

tensorx , tensory

cuda


(tensor([[0.1147, 0.3168, 0.6965],
         [0.9143, 0.9351, 0.9412]], device='cuda:0'),
 tensor([[0.5995, 0.0652, 0.5460],
         [0.1872, 0.0340, 0.9442]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [30]:
# Perform matmul on tensor_A and tensor_B
z = torch.matmul(tensorx,tensory.T)
z,z.shape

(tensor([[0.4697, 0.6899],
         [1.1230, 1.0917]], device='cuda:0'), torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [31]:
# Find max
max =torch.max(z)
# Find min
min = torch.min(z)
max,min

(tensor(1.1230, device='cuda:0'), tensor(0.4697, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [32]:
# Find arg max
argmax = torch.argmax(z)

# Find arg min
argmin = torch.argmin(z)

argmax,argmin

(tensor(2, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [37]:
# Set seed
seed = 7

# Create random tensor
torch.cuda.manual_seed(seed)
a= torch.rand(1,1,1,10)
torch.cuda.manual_seed(seed)


# Remove single dimensions
b= torch.squeeze(torch.squeeze(torch.squeeze(a,0)))

# Print out tensors and their shapes
a,a.shape,b,b.shape

(tensor([[[[0.2560, 0.7366, 0.0204, 0.2036, 0.3748, 0.2564, 0.3251, 0.0902,
            0.3936, 0.6069]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.2560, 0.7366, 0.0204, 0.2036, 0.3748, 0.2564, 0.3251, 0.0902, 0.3936,
         0.6069]),
 torch.Size([10]))