In [ ]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
print(torch.__version__)


1.13.1+cu116


In [ ]:
#creating a tensor using pytorch
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
tensor = torch.tensor([[[1,2,3],
                       [3,4,5],
                       [7,8,9]]])

tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]]])

In [ ]:
tensor.ndim 

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0][0][0] 

tensor(1)

### RANDOM TENSORS

why random tensors ?

random tensors are important because the way neural network learn is that they start with tensors full of random number and then adjust those numbers to better represent the data.

`start with a random data -> look at the data-> update random numbers -> look at data -> update random numbers  `

In [ ]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5794, 0.6263, 0.5922, 0.9681],
        [0.0516, 0.8034, 0.3569, 0.2021],
        [0.8806, 0.2409, 0.5144, 0.2735]])

In [ ]:
#create a random tensor with similar shape to an image tensor
random_imagesize_tensor = torch.rand(size= (3,224,224))
random_imagesize_tensor.shape,random_imagesize_tensor.ndim

(torch.Size([3, 224, 224]), 3)

#zero and ones

In [ ]:
zeros =  torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
### creating a range of tensors and tensors-like
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to__ten = torch.arange(start=0,end=11,step = 1)
one_to__ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tensor like
ten_zeros = torch.zeros_like(input=one_to__ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#Tensor datatypes
**NOTE** : tensor datatypes is one of the big errors you'll run into Pytorch and DeepLearning:
1. Tensors not right datatype `tensor.dtype`
2. Tensors not right shape`tensor.shape` 
3. Tensors not on the right device`tensor.device`

In [ ]:
#float 32 tensor
float_32 =torch.tensor([3.0,16,9.0],dtype=None,#what datatype is the tensor(eg. float32 or float16)
                      device=None,#what device is your tensor
                      requires_grad=False)#whether or not track gradients with this tensor equations
float_32

tensor([ 3., 16.,  9.])

In [ ]:
int_32 = float_32.type(torch.int32)
int_32 

tensor([ 3, 16,  9], dtype=torch.int32)

In [ ]:
x = int_32*float_32
x.dtype

torch.float32

In [ ]:
some = torch.rand(3,4)
some

tensor([[0.1077, 0.4514, 0.8137, 0.3422],
        [0.8970, 0.7217, 0.9320, 0.4450],
        [0.4446, 0.7536, 0.5733, 0.4075]])

In [ ]:
some.size,some.shape,some.device,some.dtype

(<function Tensor.size>, torch.Size([3, 4]), device(type='cpu'), torch.float32)

### manuplating tensors (operations)
* add  
* sub 
* mul (element wise)
* div
* matrix_mul

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor /10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
#try out pytorch in built functions 
torch.mul(tensor,10)

tensor([10, 20, 30])

###matrix multiplication 
####2 types of multipliction
1. element wise 
2. matrix multiplication (dot product)

there are two main rules that performing matrix multiplication needs to satisfy :

1. the **inner dimension** must match:
* `(3,2) @ (3,2) ` wont work
* `(2,3) @(3,2) ` will work
* `(3,2) @ (2 ,3)` will work

2. the resulting matrix has the shape of the ** outer dimension **
* `(2,3) @ (3,2)` ->(2,2)
* `(3,2) @ (2,3)` ->(3,3)


In [ ]:
#element wise 
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [ ]:
#matrix mul
torch.matmul(tensor,tensor)
tensor.shape 

torch.Size([3])

#### One of the common errors in deep learning : shape error

In [ ]:
#shape for matrix multiplication
tensor_A = torch.rand(3,2)
tensor_b = torch.rand(2,3)
torch.matmul(tensor_A,tensor_b)

tensor([[0.2083, 0.3727, 0.7455],
        [0.2890, 0.2957, 0.6099],
        [0.2506, 0.2742, 0.5630]])

### to fix our tensor shape issues , we can manipulate the shape of one of our tensors using transpose.

A transpose switches the axes or dimensions of the givem tensor.

In [ ]:
tensor_b.T

tensor([[0.0316, 0.4435],
        [0.2941, 0.3472],
        [0.5686, 0.7317]])

In [ ]:
torch.matmul(tensor_A,tensor_b.T)

RuntimeError: ignored

## reshaping , Stacking , Squeezing and Unsqueezing

* Reshaping  - Reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* stacking  - combine multiple tensor on top of each other (vstack) or side by side (hstack)
* squeeze - removes all '1' dimensions from the tensor
* unsqueeze - add a '1' dimension to  a target tensor
* permute - return a view of the input with dimension permuted

In [ ]:
import torch 
x = torch.arange(1.,9.)
x,x.shape

In [ ]:
#add an extra dimension
x_reshape = x.reshape(1,8)
x_reshape, x_reshape.shape


In [ ]:
#change the view 
z = x.view(1,8)
z,z.shape

In [ ]:
z[:,0] =5
z,x

In [ ]:
# stack tensor on top of each other
X_stacked = torch.stack([x,x,x,x],dim = 0)
X_stacked

In [ ]:
#squeezetensor
y = torch.squeeze(x_reshape,0)
xsqueezed  = x_reshape.squeeze()
y , y.shape,xsqueezed,xsqueezed.shape


In [ ]:
#unsqueeze 
print(f"pervious target : {xsqueezed}")
print(f"pervious shape : {xsqueezed.shape }")
xunsqueezed = xsqueezed.unsqueeze(dim = 0)
print(f"new target : {xunsqueezed}")
print(f"new shape : {xunsqueezed.shape }")

In [ ]:
#torch.permute - rearrages the target tensor with specified order
x_original = torch.rand(size = (224,224,3)) #[height , width , color channels]\

#permute the original tensor to rearrage the axis order
xpermuted = x_original.permute(2,0,1)
print("pervious shape",x_original.shape)
print("new shape", xpermuted.shape) #[color channels,height , width]\

In [ ]:
x_original[0,0,0] =74
xpermuted[0,0,0]

## Indexing (selecting data from tensor)

indexing with pytorch is similar to Numpy

In [ ]:
#create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

In [ ]:
#lets index on our new tensor
x[0]

In [ ]:
#lets index on middle bracket dim =1
x[0][0]

In [ ]:
#lets index on the last bracket
x[0][0][0]

In [ ]:
#you can also use  " : " to select all the  target dimension
x[:,0]

In [ ]:
x[:]

In [ ]:
#get all values of 0 dimension but only the 1 value of 1st and 2nd dimension
x[:,1,1]

In [ ]:
# get index 0 of 0th and  1st and all value of 2nd dimension
x[0,0,:]


In [ ]:
#H/W 
#index on x to return 9
x[:,:,2]
#index on x to return 3,6,9
x[:,:,2],x[:,:,2]

## pytorch tensors and numpy
numpy is popluar scientific python numerical computing library.

and because of this , pytorch has functionality to interact with it.

* Data in numpy , want in pytorch tensor -> `torch.from_numpy(ndarray)`

* pytorch tensor -> numpy  -> `torch.tensor.numpy`




In [ ]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #warning when converting numpy to pytorch 
                              # pytorch reflects numoys default datatype of float64 unless specified otherwise
                              # to change to float32 torch.from_numpy(ndarray).type(torch.float32)

array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#change the value of array it doesnt change in tensor
array = array +1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor ,numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

In [ ]:
tensor = tensor +1
tensor , numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)
in short how a neural network learns :
` start with random number -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ... `

to reduce the randomness in neural network and pytorch comes the concept of a **random seed**.
Essentially what the random seeds does is  "flavor" the randomness.


In [ ]:
import torch
randomA = torch.rand(3,4)
randomB = torch.rand(3,4)

print(randomA)
print(randomB)
print(randomA == randomB)


tensor([[0.6759, 0.8713, 0.7946, 0.4145],
        [0.2349, 0.3061, 0.3438, 0.6581],
        [0.5446, 0.6816, 0.7279, 0.3050]])
tensor([[0.8549, 0.4042, 0.3248, 0.0094],
        [0.4535, 0.3581, 0.6629, 0.2284],
        [0.4035, 0.5743, 0.5710, 0.3746]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# lets's make some random but reproducible tensor
import torch

Random_seed = 42

torch.manual_seed(Random_seed)
randomc = torch.rand(3,4)

torch.manual_seed(Random_seed)
randomd = torch.rand(3,4)

print(randomc)
print(randomd)
print(randomc == randomd)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytorch objects  on GPUs (and making faster computations)

1. easiest - use google colab   
2. use your own

3. use cloud computing - GCP,AWS.Azure.

for 2,3 see the pytorch documentation to setup cuda


In [ ]:
!nvidia-smi

Sun Jan 29 23:55:06 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P0    25W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. check for gpu acess with pytorch

In [ ]:
import torch
torch.cuda.is_available()

True

For pytorch since its capable of running compute on the GPU or CPU, its best practice to setup device agnostic code :
https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [ ]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#count the number of devices 
torch.cuda.device_count()


1

### Putting tensors (and modules) on  the GPU
the reason we want our tensors/models on GPU is because using a GPU results in faster computations.

In [ ]:
# create a tensor (default on the cpu)
tensor = torch.tensor([1,2,3],device = 'cpu')

#tensor not On GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#move tensor to GPU (if available)
tensorgpu = tensor.to(device)
tensorgpu

tensor([1, 2, 3], device='cuda:0')

## moving Tensors back to the CPU

In [ ]:
tensorgpu.numpy()


TypeError: ignored

In [ ]:
#to fix the numpy problem 
tensorback = tensorgpu.cpu().numpy()
tensorback

array([1, 2, 3])